
# BossBB ALL #
[chu]
shuffle = [ 'Standby_chu', 'CarboHydroM_chu', 'AlexMoukala_chu', 'FuegoRedXIII_chu', 'DLPBPro_chu', 'ReduxChrisMarsh_chu', 'FuegoRedXIII2_chu', 'ToxicEternity_chu', 'Tsunamods_chu', 'EHWButler_chu', 'FinalFantim_chu', 'VicenteBravo_chu', 'DLPBOST_chu', 'DLPBFan_chu', 'TheRunawayFive_chu', 'Falkkone_chu', 'RichardBichler_chu', 'ArtificialFear_chu', 'LevoLution_chu', 'DanielTidwell_chu', 'zircon_chu', 'RichardBichlerDupe_chu', 'Ferdk_chu' ]

# VictoryFA Arranged #
[fan2]
shuffle = [ 'FinalFantim_fan', 'ReduxChrisMarsh_fan', 'DLBPOST_fan', 'DLBPPro_fan', 'Tsunamods_fan', 'VicenteBravo_fan' ]

