
# BattleBA Remix #
[bat]
shuffle = [ 'ZachPayne_bat', 'Mykah_bat', 'Lau_bat' ]

# VictoryFA Arranged #
[fan2]
shuffle = [ 'FinalFantim_fan', 'ReduxChrisMarsh_fan', 'DLBPOST_fan', 'DLBPPro_fan', 'Tsunamods_fan', 'VicenteBravo_fan' ]

