
# BattleBA ALL #
[bat]
shuffle = [ 'DanielLambie_bat', 'DanielLambie2_bat', 'FinalFantim_bat', 'DanielTidwell_bat', 'Falkkone_bat', 'Ferdk_bat', 'Ferdk2_bat', 'GlitchxCity_bat', 'Huskybythegeek_bat', 'Lau_bat', 'JonnyAtama_bat', 'Pillars_bat', 'ArtificialFear_bat', 'Fishy_bat', 'Fishy2_bat', 'norg_bat', 'AlanBuono_bat', 'RichardBichler_bat', 'SheetMusicBoss_bat', 'ReduxChrisMarsh_bat', 'ToxicxEternity_bat', 'VincentMoretto_bat', 'ZachPayne_bat', 'DLBPOST_bat', 'Tsunamods_bat', 'VicenteBravo_bat', 'Mykah_bat', 'AlexMoukala_bat', 'GirlzMelon_bat', 'DLBPFan_bat', 'DLBPPro_bat', 'FamilyJules7x_bat' ]

# BossBB ALL #
[chu]
shuffle = [ 'Standby_chu', 'CarboHydroM_chu', 'AlexMoukala_chu', 'FuegoRedXIII_chu', 'DLPBPro_chu', 'ReduxChrisMarsh_chu', 'FuegoRedXIII2_chu', 'ToxicEternity_chu', 'Tsunamods_chu', 'EHWButler_chu', 'FinalFantim_chu', 'VicenteBravo_chu', 'DLPBOST_chu', 'DLPBFan_chu', 'TheRunawayFive_chu', 'Falkkone_chu', 'RichardBichler_chu', 'ArtificialFear_chu', 'LevoLution_chu', 'DanielTidwell_chu', 'zircon_chu', 'RichardBichlerDupe_chu', 'Ferdk_chu' ]

