
# BossBB Arranged #
[chu]
shuffle = [ 'AlexMoukala_chu', 'FuegoRedXIII_chu', 'ReduxChrisMarsh_chu', 'FuegoRedXIII2_chu', 'Tsunamods_chu', 'FinalFantim_chu', 'VicenteBravo_chu', 'DLPBOST_chu', 'DLPBFan_chu', 'TheRunawayFive_chu' ]

# VictoryFA Arranged #
[fan2]
shuffle = [ 'FinalFantim_fan', 'ReduxChrisMarsh_fan', 'DLBPOST_fan', 'DLBPPro_fan', 'Tsunamods_fan', 'VicenteBravo_fan' ]

