
# BattleBA Remix #
[bat]
shuffle = [ 'ZachPayne_bat', 'Mykah_bat', 'Lau_bat' ]

# BossBB Arranged #
[chu]
shuffle = [ 'AlexMoukala_chu', 'FuegoRedXIII_chu', 'ReduxChrisMarsh_chu', 'FuegoRedXIII2_chu', 'Tsunamods_chu', 'FinalFantim_chu', 'VicenteBravo_chu', 'DLPBOST_chu', 'DLPBFan_chu', 'TheRunawayFive_chu' ]

