
# BattleBA ALL #
[bat]
shuffle = [ 'DanielLambie_bat', 'DanielLambie2_bat', 'FinalFantim_bat', 'DanielTidwell_bat', 'Falkkone_bat', 'Ferdk_bat', 'Ferdk2_bat', 'GlitchxCity_bat', 'Huskybythegeek_bat', 'Lau_bat', 'JonnyAtama_bat', 'Pillars_bat', 'ArtificialFear_bat', 'Fishy_bat', 'Fishy2_bat', 'norg_bat', 'AlanBuono_bat', 'RichardBichler_bat', 'SheetMusicBoss_bat', 'ReduxChrisMarsh_bat', 'ToxicxEternity_bat', 'VincentMoretto_bat', 'ZachPayne_bat', 'DLBPOST_bat', 'Tsunamods_bat', 'VicenteBravo_bat', 'Mykah_bat', 'AlexMoukala_bat', 'GirlzMelon_bat', 'DLBPFan_bat', 'DLBPPro_bat', 'FamilyJules7x_bat' ]

# VictoryFA ALL #
[fan2]
shuffle = [ 'FinalFantim_fan', 'ReduxChrisMarsh_fan', 'AnotherSoundscape_fan', 'FamilyJules7x_fan', 'aluminum_fan', 'DjCutman_fan', 'DjCutman2_fan', 'Mykah_fan', 'HolderEphixa_fan', 'HolderEphixa2_fan', 'DLBPOST_fan', 'DLBPPro_fan', 'FredrikHagglund_fan', 'TheRunawayFive_fan', 'Tsunamods_fan', 'VicenteBravo_fan', 'Pillars_fan', 'DanielLambie_fan', 'GirlzMelon_fan', 'GirlzMelon2_fan', 'DjCutman3_fan', 'DjCutman4_fan', 'Carlucci_fan', 'AnotherSoundscape2_fan', 'aluminum2_fan' ]

