
# BattleBA Remix #
[bat]
shuffle = [ 'ZachPayne_bat', 'Mykah_bat', 'Lau_bat' ]

# BossBB Metal #
[chu]
shuffle = [ 'DLPBPro_chu', 'ToxicEternity_chu', 'EHWButler_chu', 'Falkkone_chu', 'RichardBichler_chu', 'ArtificialFear_chu', 'DanielTidwell_chu', 'RichardBichlerDupe_chu', 'Ferdk_chu' ]

