
# BossBB Metal #
[chu]
shuffle = [ 'DLPBPro_chu', 'ToxicEternity_chu', 'EHWButler_chu', 'Falkkone_chu', 'RichardBichler_chu', 'ArtificialFear_chu', 'DanielTidwell_chu', 'RichardBichlerDupe_chu', 'Ferdk_chu' ]

# VictoryFA Remix #
[fan2]
shuffle = [ 'AnotherSoundscape_fan', 'aluminum_fan', 'DjCutman_fan', 'DjCutman2_fan', 'Mykah_fan', 'HolderEphixa_fan', 'HolderEphixa2_fan', 'TheRunawayFive_fan', 'DjCutman3_fan', 'DjCutman4_fan', 'AnotherSoundscape2_fan', 'aluminum2_fan' ]

