
# BattleBA Arranged #
[bat]
shuffle = [ 'DLBPPro_bat', 'FinalFantim_bat', 'AlanBuono_bat', 'SheetMusicBoss_bat', 'ReduxChrisMarsh_bat', 'VincentMoretto_bat', 'DLBPOST_bat', 'Tsunamods_bat', 'VicenteBravo_bat', 'AlexMoukala_bat', 'DLBPFan_bat' ]

# BossBB Metal #
[chu]
shuffle = [ 'DLPBPro_chu', 'ToxicEternity_chu', 'EHWButler_chu', 'Falkkone_chu', 'RichardBichler_chu', 'ArtificialFear_chu', 'DanielTidwell_chu', 'RichardBichlerDupe_chu', 'Ferdk_chu' ]

# VictoryFA Arranged #
[fan2]
shuffle = [ 'FinalFantim_fan', 'ReduxChrisMarsh_fan', 'DLBPOST_fan', 'DLBPPro_fan', 'Tsunamods_fan', 'VicenteBravo_fan' ]

