
# BattleBA Arranged #
[bat]
shuffle = [ 'DLBPPro_bat', 'FinalFantim_bat', 'AlanBuono_bat', 'SheetMusicBoss_bat', 'ReduxChrisMarsh_bat', 'VincentMoretto_bat', 'DLBPOST_bat', 'Tsunamods_bat', 'VicenteBravo_bat', 'AlexMoukala_bat', 'DLBPFan_bat' ]

# BossBB Remix #
[chu]
shuffle = [ 'Standby_chu', 'CarboHydroM_chu', 'LevoLution_chu', 'zircon_chu' ]

# VictoryFA Metal #
[fan2]
shuffle = [ 'GirlzMelon_fan', 'GirlzMelon2_fan', 'FamilyJules7x_fan', 'FredrikHagglund_fan', 'Pillars_fan', 'DanielLambie_fan', 'Carlucci_fan' ]

