
# BattleBA Metal #
[bat]
shuffle = [ 'RichardBichler_bat', 'FamilyJules7x_bat', 'GirlzMelon_bat', 'ToxicxEternity_bat', 'norg_bat', 'Fishy_bat', 'ArtificialFear_bat', 'DanielLambie_bat', 'DanielLambie2_bat', 'DanielTidwell_bat', 'Falkkone_bat', 'Ferdk_bat', 'Ferdk2_bat', 'GlitchxCity_bat', 'Huskybythegeek_bat', 'JonnyAtama_bat', 'Pillars_bat', 'Fishy2_bat' ]

# BossBB Metal #
[chu]
shuffle = [ 'DLPBPro_chu', 'ToxicEternity_chu', 'EHWButler_chu', 'Falkkone_chu', 'RichardBichler_chu', 'ArtificialFear_chu', 'DanielTidwell_chu', 'RichardBichlerDupe_chu', 'Ferdk_chu' ]

# VictoryFA Metal #
[fan2]
shuffle = [ 'GirlzMelon_fan', 'GirlzMelon2_fan', 'FamilyJules7x_fan', 'FredrikHagglund_fan', 'Pillars_fan', 'DanielLambie_fan', 'Carlucci_fan' ]

