
# BossBB Arranged #
[chu]
shuffle = [ 'AlexMoukala_chu', 'FuegoRedXIII_chu', 'ReduxChrisMarsh_chu', 'FuegoRedXIII2_chu', 'Tsunamods_chu', 'FinalFantim_chu', 'VicenteBravo_chu', 'DLPBOST_chu', 'DLPBFan_chu', 'TheRunawayFive_chu' ]

# VictoryFA ALL #
[fan2]
shuffle = [ 'FinalFantim_fan', 'ReduxChrisMarsh_fan', 'AnotherSoundscape_fan', 'FamilyJules7x_fan', 'aluminum_fan', 'DjCutman_fan', 'DjCutman2_fan', 'Mykah_fan', 'HolderEphixa_fan', 'HolderEphixa2_fan', 'DLBPOST_fan', 'DLBPPro_fan', 'FredrikHagglund_fan', 'TheRunawayFive_fan', 'Tsunamods_fan', 'VicenteBravo_fan', 'Pillars_fan', 'DanielLambie_fan', 'GirlzMelon_fan', 'GirlzMelon2_fan', 'DjCutman3_fan', 'DjCutman4_fan', 'Carlucci_fan', 'AnotherSoundscape2_fan', 'aluminum2_fan' ]

