
# BattleBA Remix #
[bat]
shuffle = [ 'ZachPayne_bat', 'Mykah_bat', 'Lau_bat' ]

# BossBB Remix #
[chu]
shuffle = [ 'Standby_chu', 'CarboHydroM_chu', 'LevoLution_chu', 'zircon_chu' ]

# VictoryFA Metal #
[fan2]
shuffle = [ 'GirlzMelon_fan', 'GirlzMelon2_fan', 'FamilyJules7x_fan', 'FredrikHagglund_fan', 'Pillars_fan', 'DanielLambie_fan', 'Carlucci_fan' ]

